version: "3.8"

services:
  jupyter-userA:
    image: jupyter-docker-demo:latest
    environment:
      - REPO_URL=https://github.com/Chelseavdm-ucd/Sand-Technologies-test
    ports:
      - "8888:8888"
    volumes:
      - /home/ec2-user/userA:/home/jovyan/work
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  jupyter-userB:
    image: jupyter-docker-demo:latest
    environment:
      - REPO_URL=https://github.com/Chelseavdm-ucd/Sand-Technologies-test
    ports:
      - "8889:8888"
    volumes:
      - /home/ec2-user/userB:/home/jovyan/work
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
